### PR TITLE
Add/update openapi-generator containers

### PR DESCRIPTION
**Pull request by mharding-hpe**
Add new versions (v6.5.0, v6.6.0) of the openapi-generator containers, and redefine the existing versions (v5.1.0, v6.4.0) using "make add" method.

### CODE REVIEW

**Comment by mtupitsyn** [comment]
@mharding-hpe Process of adding images to this repo was completely revamped by @mitchty , so I'd delegate PR review to him... As far as I can see, the files in this PR were generated the old way (by running `create_buildfiles.sh`) and they are supposed to be ran by running `make add` now.

**Comment by mharding-hpe** [comment]
Ok, I've recreated them using the "make add" procedure.

**Comment by mharding-hpe** [comment]
Interesting. In this version of the PR, the jobs are failing. Let me investigate...

**Comment by mharding-hpe** [comment]
I think running the make under Ubuntu was not working. Tried it under SLES and it went more smoothly.

**Comment by mharding-hpe** [comment]
Now they are failing on Snyk failures. I'm wondering if it's okay for us to allow these anyway, since we don't actually ship these containers as part of CSM -- they're just used by us at build time to generate API framework files. So we don't need to worry about malicious actors making use of them.

**Comment by mharding-hpe** [comment]
Talked to @mitchty . He said to go ahead and manually edit the jobs for these guys to not fail on Snyk failures. I have done so.

**Review by mitchty — APPROVED** [review]

**Pull request merged**
