### PR TITLE
Add k8s 1.22.13, 1.23.10, 1.24.4, 1.25.0

### PR DESCRIPTION
**Pull request by mitchty**
While none will yet be used trying to shake out any/all issues with containers before we need or use them.

## Summary and Scope

Add future k8s images and make it easier to update them with a script tailored a bit for this purpose. This is just the result of running:

```
for x in 1.22.13 1.23.10 1.24.4 1.25.0; do
k8sversion=${x} ./k8s.sh
done
```
And committing the files. Note for anything beyond 1.22.13 we likely won't be using the exact images here but we want to find and shake out any/all image issues before we need them.

This is backwards compatible as only I will be using these images for now for testing purposes and shaking out any issues found.

## Issues and Related PRs

_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._

* Resolves [CASM-3384](https://jira-pro.its.hpecorp.net:8443/browse/CASM-3384)
* Change will also be needed in `<insert branch name here>`
* Future work required by [issue id](issue link)
* Documentation changes required in [issue id](issue link)
* Merge with/before/after `<insert PR URL here>`

## Testing

n/a Putting in place to allow testing 1.22 and/or finding out if we can do multiple version hops of k8s in the future and if so what we can or cannot hop to.

### Tested on:

 n/a will be abusing vshasta and redbull most likely to validate these images.

### Test description:

n/a Need these images in place in algol60 to do testing later, they aren't used by anyone yet.

- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?
- Were continuous integration tests run? If not, why?
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?
- Were new tests (or test issues/Jiras) created for this change?

## Risks and Mitigations

Only if people start trying to use these otherwise no risk.

## Pull Request Checklist

- [ ] Version number(s) incremented, if applicable
- [ ] Copyrights updated
- [ ] License file intact
- [ ] Target branch correct
- [ ] CHANGELOG.md updated
- [ ] Testing is appropriate and complete, if applicable
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

### CODE REVIEW

**Comment by kburns-hpe** [comment]
Looks like kube-proxy:v1.25.0 got rid of apt-get.

**Review by bklei — DISMISSED** [review]

**Comment by mitchty** [comment]
Looking at 1.25.0, its not critical I include that one it removes PSP's so it definitely will break stuff, will see if they changed kube-proxy from a debian base there I hadn't looked.

**Comment by mitchty** [comment]
Yep looks like in 1.25.0 kube-proxy is distroless https://github.com/kubernetes/kubernetes/blob/a304fdd8671873d80ba8a0579298d0b5aaa2d91e/CHANGELOG/CHANGELOG-1.25.md#kube-proxy-images-are-now-based-on-distroless-images

**Review by kburns-hpe — APPROVED** [review]

**Comment by mitchty** [comment]
Heh well that'll learn me to force push still picks up the old file contents.

**Comment by mitchty** [comment]
License check passed just not updating.

**Pull request merged**
