### PR TITLE
CASMMON-244: Update Prometheus to current stable release version v2.41.0

### PR DESCRIPTION
**Pull request by sumithrb**
## Summary and Scope
Prometheus updated to the current stable version v2.41.0, alert manager to v0.25.0, and node-exporter to v1.5.0.
Backward compatible.

* Resolves - [CASMMON-244](https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-244)

### Tested on:
  * `mug` successfully

Snips of the testing -
image
image
image
image
image

### Test description:
How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?
- Upgrade was tested.

prometheus_build_info{branch="HEAD", endpoint="web", goarch="amd64", goos="linux", goversion="go1.19.4", instance="10.44.0.2:9090", job="cray-sysmgmt-health-promet-prometheus", namespace="sysmgmt-health", pod="prometheus-cray-sysmgmt-health-promet-prometheus-0", revision="c0d8a56c69014279464c0e15d8bfb0e153af0dab", service="cray-sysmgmt-health-promet-prometheus", version="2.41.0"}

alertmanager_build_info{branch="HEAD", endpoint="web", goversion="go1.19.4", instance="10.34.0.42:9093", job="cray-sysmgmt-health-promet-alertmanager", namespace="sysmgmt-health", pod="alertmanager-cray-sysmgmt-health-promet-alertmanager-0", revision="258fab7cdd551f2cf251ed0348f0ad7289aee789", service="cray-sysmgmt-health-promet-alertmanager", version="0.25.0"}

node_exporter_build_info{branch="HEAD", endpoint="metrics", goversion="go1.19.3", instance="10.252.1.10:9100", job="node-exporter", namespace="sysmgmt-health", pod="cray-sysmgmt-health-prometheus-node-exporter-9mmgc", revision="1b48970ffcf5630534fb00bb0687d73c66d1c959", service="cray-sysmgmt-health-prometheus-node-exporter", version="1.5.0"}

## Risks and Mitigations
Are there known issues with these changes? Any other special considerations?
No.

## Pull Request Checklist

- [x] Version number(s) incremented, if applicable
- [x] Testing is appropriate and complete, if applicable

### CODE REVIEW

**Review by rambabubolla — APPROVED** [review]

**Comment by jhansonhpe** [comment]
The current upstream version is 2.41.0. Please use that instead.
https://quay.io/repository/prometheus/prometheus?tab=tags
I also want the rest of the prometheus code updated to current. This means alertmanager and node exporter at least.

**Comment by sumithrb** [comment]
> The current upstream version is 2.41.0. Please use that instead. https://quay.io/repository/prometheus/prometheus?tab=tags I also want the rest of the prometheus code updated to current. This means alertmanager and node exporter at least.

Sure, let me make the changes to this PR to use 2.41.0 and update alertmanager and node exporter as well.

**Comment by jhansonhpe** [comment]
Can you explain why use of quay.io versus https://hub.docker.com/u/prom which seems to be the official place per https://prometheus.io/download/ ?

**Comment by sumithrb** [comment]
> Can you explain why use of quay.io versus https://hub.docker.com/u/prom which seems to be the official place per https://prometheus.io/download/ ?

Old engineers used that path. Slant community recommends quay.io.

**Comment by jhansonhpe** [comment]
Who or what is the slant community?

**Comment by sumithrb** [comment]
> Who or what is the slant community?

Slant (https://www.slant.co/) is a product recommendation community with the goal of making it effortless to find the best product or app for you. Quay.io is ranked 4th while Docker Hub Registry is ranked 8th. Still the main reason being old engineers used that path and we continued using the same.

**Review by rambabubolla — APPROVED** [review]

**Review by shreni123 — APPROVED** [review]

**Pull request merged**
